# Computational Electrodynamics - 02 _  Activity 1

# Solving Linear equations

In [ ]:
import numpy as np

A = np.array([[10 ,-1 ,2], [-1, 11 , -1], [2, -1, 10]])
Y = np.array([[6], [22], [-10]])

# Y = AX   X= [x,y,z]
X = np.linalg.solve(A, Y)

print(X)

[[ 1.]
 [ 2.]
 [-1.]]


# Jacobian Iterations

In [ ]:
def jacobi(A, b, ep, x0, Imax):

    M = np.diag(np.diag(A))
    E = (-1) * np.tril(A - M)
    F = (-1) * np.triu(A - M)
    N = E + F

    vp = np.linalg.eigvals(np.dot(np.linalg.inv(M), N))
    rho = np.max(np.abs(vp))

    iter = 0
    x = x0

    while iter < Imax and np.max(abs(b - np.dot(A, x))) > ep:
        iter = iter + 1

        x = np.dot(
            np.linalg.inv(M),
            np.dot(N, x) + b
        )

    x_e = np.linalg.solve(A, b)
    err = np.linalg.norm(x_e - x)

    return [x, x_e, err, iter]


ep = 0.000001
max_iter = 1000
#Initial guess
x0 = np.zeros(3)

A = np.array([[10 ,-1 ,2], [-1, 11 , -1], [2, -1, 10]])

Y = np.array([[6], [22], [-10]])

X,X_e, Err, Iter = jacobi(A, Y, ep, x0, max_iter)
print('\n Solution with Jacobi method')
print(X) 
print('\n Solution by solving the system of equations using matrix inversion')
print(X_e)
print('\n Error')
print(Err)
print('\n Number of iterations')
print(Iter)



 Solution with Jacobi method
[[ 0.99999998  0.99999998  0.99999998]
 [ 2.00000001  2.00000001  2.00000001]
 [-1.00000002 -1.00000002 -1.00000002]]

 Solution by solving the system of equations using matrix inversion
[[ 1.]
 [ 2.]
 [-1.]]

 Error
5.921890310957134e-08

 Number of iterations
13


# Gauss-Seidel method

In [ ]:
import numpy as np

def seidel(a, x, b):
    n = len(a)

    for j in range(0, n):
        d = b[j]

        for i in range(0, n):
            if j != i:
                d -= a[j][i] * x[i]

        x[j] = d / a[j][j]

    return x

# Initial guess
x_seidel = np.zeros(3)

A = np.array([[10 ,-1 ,2], [-1, 11 , -1], [2, -1, 10]])
Y = np.array([6, 22, -10])

n = len(A)

print(x_seidel)

max_iter = 25

for i in range(0, max_iter):
    x_seidel = seidel(A, x_seidel, Y)
    print(x_seidel)

[0. 0. 0.]
[ 0.6         2.05454545 -0.91454545]
[ 0.98836364  2.00671074 -0.99700165]
[ 1.0000714   2.00027907 -0.99998637]
[ 1.00002518  2.00000353 -1.00000468]
[ 1.00000129  1.99999969 -1.00000029]
[ 1.00000003  1.99999998 -1.00000001]
[ 1.  2. -1.]
[ 1.  2. -1.]
[ 1.  2. -1.]
[ 1.  2. -1.]
[ 1.  2. -1.]
[ 1.  2. -1.]
[ 1.  2. -1.]
[ 1.  2. -1.]
[ 1.  2. -1.]
[ 1.  2. -1.]
[ 1.  2. -1.]
[ 1.  2. -1.]
[ 1.  2. -1.]
[ 1.  2. -1.]
[ 1.  2. -1.]
[ 1.  2. -1.]
[ 1.  2. -1.]
[ 1.  2. -1.]
[ 1.  2. -1.]
